@baseUrl = http://localhost:3000/api/v1

### Get Users
GET {{ baseUrl }}/users

### Get User by ID
GET {{ baseUrl }}/users/1

### Create User
POST {{ baseUrl }}/users
Content-Type: application/json

{
  "nationalIdentityNumber": "8276578943746538",
  "name": "Choirul Anam",
  "email": "test2@example.com",
  "password": "anam1234",
  "gender": "MALE",
  "birthday": "1990-01-01T00:00:00.000Z",
  "birthplace": "New York",
  "religion": "CHRISTIAN",
  "maritalStatus": "MARRIED",
  "education": "BACHELOR",
  "job": "STUDENT",
  "family": {
    "connect": { "id": 3 }
  }
}


### Update User
PATCH  {{ baseUrl }}/users/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1Mzg1MDM2OCwiZXhwIjoxNzUzODUzOTY4fQ.QWFQXL1k5hyJifvurhfmb5kIilX9ins8ve9w50mFZ7Y
Content-Type: application/json

{
  "name": "Choirul Anam Updated"
}

### Delete User
DELETE {{ baseUrl }}/users/3

### Login User
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "anam1234"
}

### Get Submissions
GET {{ baseUrl }}/submissions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1Mzg1MTEyNiwiZXhwIjoxNzUzODU0NzI2fQ.RK7I7nHu2_MT6B3trrMZD6l8Ql7CP9lB9l0dk0_11gQ

### Create Submission
POST {{ baseUrl }}/submissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1Mzg1MDM2OCwiZXhwIjoxNzUzODUzOTY4fQ.QWFQXL1k5hyJifvurhfmb5kIilX9ins8ve9w50mFZ7Y
Content-Type: application/json

{
  "title": "Submission Title 2",
  "date": "1990-01-01T00:00:00.000Z",
  "category": "DOMICILE_CERTIFICATE",
  "status": "PENDING",
  "description": "This is a test submission.",
  "userId": 6
}

### Update Submission
PATCH {{ baseUrl }}/submissions/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1Mzg1MDM2OCwiZXhwIjoxNzUzODUzOTY4fQ.QWFQXL1k5hyJifvurhfmb5kIilX9ins8ve9w50mFZ7Y
Content-Type: application/json

{
  "title": "Updated Submission Title",
  "description": "This is an updated test submission."
}

### Update status of Submission
PATCH {{ baseUrl }}/submissions/5/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1Mzg0NDYwNywiZXhwIjoxNzUzODQ4MjA3fQ.uU6-oHtm37VlVPTOXwwtwtrajqxy_0sIesCeIwSz9Z0
Content-Type: application/json

{
  "status": "COMPLETED"
}

### Delete Submission
DELETE {{ baseUrl }}/submissions/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1Mzg0NDYwNywiZXhwIjoxNzUzODQ4MjA3fQ.uU6-oHtm37VlVPTOXwwtwtrajqxy_0sIesCeIwSz9Z0
