@baseUrl = http://localhost:3000/api/v1
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTY5NDYwMjUsImV4cCI6MTc1Njk0OTYyNX0.Ykh3AjiDUIcZekyvr4orJQh_ou7JUhHkfCkPKJXG57E

### Login User
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "anam1234"
}

### 
GET {{baseUrl}}/facilities
Authorization: {{token}}

###
GET {{baseUrl}}/facilities/1
Authorization: {{token}}

###
POST {{baseUrl}}/facilities
Authorization: {{token}}
Content-Type: application/json

{
   "name": "facility 1",
   "description": "test desc",
   "latitude": 234.21312,
   "longitude": 324.23423,
   "buildDate": "1990-01-01T00:00:00.000Z"
}

###
PATCH {{baseUrl}}/facilities/1
Authorization: {{token}}
Content-Type: application/json

{
   "name": "facility updated"
}

###
DELETE {{baseUrl}}/facilities/2
Authorization: {{token}}