@baseUrl = http://localhost:3000/api/v1
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTY5NDYwMjUsImV4cCI6MTc1Njk0OTYyNX0.Ykh3AjiDUIcZekyvr4orJQh_ou7JUhHkfCkPKJXG57E
### Login User
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "anam1234"
}

###
GET {{baseUrl}}/families
Authorization: {{ token }}

###
GET {{baseUrl}}/families/3
Authorization: {{ token }}

###
POST {{baseUrl}}/families
Authorization: {{ token }}
Content-Type: application/json

{
   "familyNumber": "7265456787653453",
   "headFamily": "Test",
   "address": "Test",
   "economicStatus": "UPPER"
}

###
PATCH {{baseUrl}}/families/3
Authorization: {{ token }}
Content-Type: application/json

{
   "headFamily": "Test updated"
}

###
DELETE {{baseUrl}}/families/4
Authorization: {{ token }}