### Login User
@baseUrl = http://localhost:8000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTgyMTUzOTQsImV4cCI6MTc1ODIxODk5NH0.qlTa0-MSdATXLat7jXE7hFHTj6cOeEnompjc76oF5EU
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "anam1234"
}

### Get News
GET {{baseUrl}}/news
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/news/9/comments
Authorization: Bearer {{token}}

### Create News
POST {{baseUrl}}/news
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "title": "News test title s",
   "date": "1990-01-01T00:00:00.000",
   "content": "News content title"
}

### Update 
PUT {{baseUrl}}/news/10
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "title": "News test title updated",
   "content": "News content title updated"
}

### Delete
DELETE {{baseUrl}}/news/6
Authorization: Bearer {{token}}