@baseUrl = http://localhost:3000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTY5NDYwMjUsImV4cCI6MTc1Njk0OTYyNX0.Ykh3AjiDUIcZekyvr4orJQh_ou7JUhHkfCkPKJXG57E

### Login User
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "anam1234"
}


### Get Report
GET {{baseUrl}}/reports?filter=IN_PROGRESS
Authorization: {{token}}

### Create report
POST {{baseUrl}}/reports
Authorization: {{token}}
Content-Type: application/json

{
  "title": "Test report",
  "description": "Test",
  "category": "INFRASTRUCTURE",
  "status": "PENDING",
  "userId": 6
}

### Update report
PATCH {{baseUrl}}/reports/1
Authorization: {{token}}
Content-Type: application/json

{
  "title": "updated title 2"
}

### update report response
PATCH {{baseUrl}}/reports/3/response
Authorization: {{token}}
Content-Type: application/json

{
  "response": "test new response",
  "status": "IN_PROGRESS"
}

### delete report response
DELETE {{baseUrl}}/reports/3
Authorization: {{token}}
