@baseUrl = http://localhost:3000/api/v1

### Login User
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "anam1234"
}


### Get Report
GET {{baseUrl}}/reports?filter=IN_PROGRESS
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTQzNzI1OTAsImV4cCI6MTc1NDM3NjE5MH0.41Ou4E5FRYC035ZAx2jmp-fpaui7QXn6kZjAcNqq9HU

### Create report
POST {{baseUrl}}/reports
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1NDM3MzEzMSwiZXhwIjoxNzU0Mzc2NzMxfQ.k52m5k_5vJleSfOnpqXRB3PHI5ZgHMY552TykZ3gj1g
Content-Type: application/json

{
  "title": "Test report",
  "description": "Test",
  "category": "INFRASTRUCTURE",
  "status": "PENDING",
  "userId": 6
}

### Update report
PATCH {{baseUrl}}/reports/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTQzNzI1OTAsImV4cCI6MTc1NDM3NjE5MH0.41Ou4E5FRYC035ZAx2jmp-fpaui7QXn6kZjAcNqq9HU
Content-Type: application/json

{
  "title": "updated title 2"
}

### update report response
PATCH {{baseUrl}}/reports/3/response
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTQzNzI1OTAsImV4cCI6MTc1NDM3NjE5MH0.41Ou4E5FRYC035ZAx2jmp-fpaui7QXn6kZjAcNqq9HU
Content-Type: application/json

{
  "response": "test new response",
  "status": "IN_PROGRESS"
}

### delete report response
DELETE {{baseUrl}}/reports/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTM4NzU3MzQsImV4cCI6MTc1Mzg3OTMzNH0.nLEUXv0V42K3CYCfgwuc6flS3waLC2mbo8nZH5umsS4
