@baseUrl = http://localhost:8000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTY5NDYwMjUsImV4cCI6MTc1Njk0OTYyNX0.Ykh3AjiDUIcZekyvr4orJQh_ou7JUhHkfCkPKJXG57E

### Login User
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "anam1234"
}

### Get Submissions
GET {{ baseUrl }}/submissions?filter=
Authorization: {{ token }}

### Create Submission
POST {{ baseUrl }}/submissions
Authorization: {{ token }}
Content-Type: application/json

{
  "title": "Submission Title 4",
  "date": "1990-01-01T00:00:00.000Z",
  "category": "DOMICILE_CERTIFICATE",
  "description": "This is a test submission.",
}

### Update Submission
PATCH {{ baseUrl }}/submissions/3
Authorization: {{ token }}
Content-Type: application/json

{
  "title": "Updated Submission Title",
  "description": "This is an updated test submission."
}

### Update status of Submission
PATCH {{ baseUrl }}/submissions/5/status
Authorization: {{ token }}
Content-Type: application/json

{
  "status": "COMPLETED"
}

### Delete Submission
DELETE {{ baseUrl }}/submissions/2
Authorization: {{ token }}