@baseUrl = http://localhost:8000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTY5NDYwMjUsImV4cCI6MTc1Njk0OTYyNX0.Ykh3AjiDUIcZekyvr4orJQh_ou7JUhHkfCkPKJXG57E

### Get Users
GET {{ baseUrl }}/users

### Get User by ID
GET {{ baseUrl }}/users/1

###
GET {{baseUrl}}/users/me
Authorization: {{ token }}


### Create User
POST {{ baseUrl }}/users
Content-Type: application/json

{
  "nationalIdentityNumber": "8276578943746538",
  "name": "Choirul Anam",
  "email": "test2@example.com",
  "password": "anam1234",
  "gender": "MALE",
  "birthday": "1990-01-01T00:00:00.000Z",
  "birthplace": "New York",
  "religion": "CHRISTIAN",
  "maritalStatus": "MARRIED",
  "education": "BACHELOR",
  "job": "STUDENT",
  "family": {
    "connect": { "id": 3 }
  }
}


### Update User
PATCH  {{ baseUrl }}/users/6
Authorization: {{ token }}

{
  "name": "Choirul Anam Updated"
}

### Delete User
DELETE {{ baseUrl }}/users/3
Authorization: {{ token }}